Update openshift.yml

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -16,8 +16,6 @@ env:
 
   # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
   APP_NAME: "blog"
-  # ROUTE: ${{ env.APP_NAME }}-route-${{ env.OPENSHIFT_NAMESPACE }}.apps.na46.prod.nextcle.com
-
 
 on:
   # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
@@ -151,12 +149,12 @@ jobs:
         retry_wait_seconds: 10
         max_attempts: 30
         warning_on_retry: false
-        command: curl -sSfLi ${{ env.ROUTE }}
+        command: curl -sSfLi ${{ env.APP_NAME }}-route-${{ env.OPENSHIFT_NAMESPACE }}.apps.na46.prod.nextcle.com
 
     - name: Print application URL
       run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        [[ -n ${{ env.APP_NAME }}-route-${{ env.OPENSHIFT_NAMESPACE }}.apps.na46.prod.nextcle.com ]] || (echo "Determining application route failed in previous step"; exit 1)
         echo
         echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
+        echo ${{ env.APP_NAME }}-route-${{ env.OPENSHIFT_NAMESPACE }}.apps.na46.prod.nextcle.com
         echo "==================================================================================="
